### ISSUE TITLE
Ability to hide empty folders

### ISSUE THREAD

**Issue by wdanilo** [ChrisFromHexx/active-files#2]
Hello! Would it be possible to ad ability to hide empty folders when all the files in a particular folder where not changed in this giit commit? That would make this plugin much more usefull to me! Thank you! :)

**Comment by ChrisFromHexx** [comment]
I'll see what I can do.

**Comment by wdanilo** [comment]
Thank you! I'll be thankful for making it possible! :)

**Comment by ChrisFromHexx** [comment]
I have just updated the active-files plugin to hide unnecessary folders.

Enjoy.

**Comment by wdanilo** [comment]
Thank you! I've just updated the plugin (to version `1.2.0`) but it doesn't seem to work for me :( In fact the behavior didn't change. When I hide the files, a lot of empty folders still appear. I attach a screenshot to show you how it looks like here (the selected `backend` folder is empty after hiding the files by your plugin. In fact all the folders below are empty too):

![screen shot 2016-04-06 at 00 31 51](https://cloud.githubusercontent.com/assets/1623053/14300206/30485e0c-fb8f-11e5-808d-bae0a0d1fdca.png)

**Comment by ChrisFromHexx** [comment]
Does toggling Shift-Alt-Cmd-R change the tree layout?

**Comment by wdanilo** [comment]
No, it doesn't change anything. I've also checked that this shortcut is NOT overridden by any other plugin / custom one.

**Comment by ChrisFromHexx** [comment]
Use the menu option Atom>Stylesheets…

If the **styles.less** file only contains my  **.tree-view…** entries; remove them, save, and then toggle  Alt-Cmd-R a couple of times.

**Comment by wdanilo** [comment]
yay! it works now! Thank you very much for making it possible! :)

**Comment by ChrisFromHexx** [comment]
What fixed it?

**Comment by wdanilo** [comment]
Your solution - I've removed all styles that was not mine and were beginning with `.tree-view'. After I saved the file and hit the shortcut to hide the files, folders was hidden too :)

**Comment by ChrisFromHexx** [comment]
Great. Happy coding. :)
